apiVersion: ENC[AES256_GCM,data:iCw=,iv:O3FYWYfBeYcahV4ZyvT4YsSXZpQ33kmD5u5BBzyFaEA=,tag:D0ua/h5KSruY0cI4waOiXg==,type:str]
kind: ENC[AES256_GCM,data:Z8HeIR0w,iv:MStJnGleiW1GPUsJO1x2nHFLGyJn2vhAeA1DNd1+WyM=,tag:DXnhb0Z6zVmfsShrjzhMWw==,type:str]
type: ENC[AES256_GCM,data:pi1iIL8aZ6Izz+KxtrJ6+hp5Vv9JzFGA,iv:GtwB82ba1faTSlmNU8xDkm41p4jBcHYifaHyvWylp3o=,tag:xQEGXEXeFK9iJiVh3P/hCw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:erguH2nFnE8VfdnUokHw8Tz7va/GT0yimuQ=,iv:wB+qeL+z/M208g0FopkbE8/njTxHbH1J/LNwjO1q4g4=,tag:2ILKbel+ZhpE5CpQEO+H0A==,type:str]
    namespace: ENC[AES256_GCM,data:urnUi1p3raU=,iv:vhXeug6/e5q878f4Lppd/p5GFn85NUN/L/crarjc8zg=,tag:ctiqhrnB4d2UQHLnFSmQ+w==,type:str]
stringData:
    username: ENC[AES256_GCM,data:xsJirD4wugUN,iv:eaflPYuLTzjsopXJ1/JaSJvAbSflmh4ugTm3wveMyjg=,tag:SwPM8OPKjhW1n5v0Xf716A==,type:str]
    password: ENC[AES256_GCM,data:p/+LuhjU+PxF/GUlHOiRoP9t6wvo/4ui/5+bF0aGslyCsb1ShMExNjlfWzE=,iv:5n0ofbnYo2aL62KxyH6zY8UzUMGgtum7MpTAVxZQ+vY=,tag:Bic+7ygc9DcH+xiDBDBh7Q==,type:str]
sops:
    age:
        - recipient: age1axd89qsnm60jcgde249ehj836cmvacfl8pxxn92xnd62d8t6rexqk5r6u8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRQTl3eDI5dUV6OEswR1pL
            Q1JBR3dUTXJuVW5kZVh4MjhBOUNTbWFwQ3hZCmV1UFB0S2RsclZtSXFOTDNqSEls
            a21KUW5EdzRtN2I1RzFwYjNNQzhPUm8KLS0tIEd4ajRkZVg4SGM3QnlRdFZNR3dr
            cFJXNXo4RTlZTjBGSXFtTUxySkZSOXMKHhu0f4mAIGnVg4RlREXVNUr7b3LRA6xA
            AEa7xLPe231kZoxetDOHpLEef7QaXVBOEW9E4EC1VWK3veUQnpWFuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-23T20:28:05Z"
    mac: ENC[AES256_GCM,data:eN+1N7iHSmk0n867DrzCjtIAErtKSsBxkz9g30XCrxF9fIJhbCToOgRva4ziPWeMl9L7Pvybf1k0TANXnz2Rdmr6cgd+ARtZk18I36n6LFiteTkAlKgtiCyRSXeOzhi59uEZp/QE7kxm/dpnc643Bzjhl89CJkVrfIvDROq5PDM=,iv:vwRcu1NNA343akKdHMQZrwF2AUy0RUMpYa7O0vsCjKI=,tag:hC+LuUpPjH3yHDyL6Vth7A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
