apiVersion: ENC[AES256_GCM,data:iCw=,iv:O3FYWYfBeYcahV4ZyvT4YsSXZpQ33kmD5u5BBzyFaEA=,tag:D0ua/h5KSruY0cI4waOiXg==,type:str]
kind: ENC[AES256_GCM,data:Z8HeIR0w,iv:MStJnGleiW1GPUsJO1x2nHFLGyJn2vhAeA1DNd1+WyM=,tag:DXnhb0Z6zVmfsShrjzhMWw==,type:str]
type: ENC[AES256_GCM,data:pi1iIL8aZ6Izz+KxtrJ6+hp5Vv9JzFGA,iv:GtwB82ba1faTSlmNU8xDkm41p4jBcHYifaHyvWylp3o=,tag:xQEGXEXeFK9iJiVh3P/hCw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:erguH2nFnE8VfdnUokHw8Tz7va/GT0yimuQ=,iv:wB+qeL+z/M208g0FopkbE8/njTxHbH1J/LNwjO1q4g4=,tag:2ILKbel+ZhpE5CpQEO+H0A==,type:str]
    namespace: ENC[AES256_GCM,data:urnUi1p3raU=,iv:vhXeug6/e5q878f4Lppd/p5GFn85NUN/L/crarjc8zg=,tag:ctiqhrnB4d2UQHLnFSmQ+w==,type:str]
stringData:
    username: ENC[AES256_GCM,data:xsJirD4wugUN,iv:eaflPYuLTzjsopXJ1/JaSJvAbSflmh4ugTm3wveMyjg=,tag:SwPM8OPKjhW1n5v0Xf716A==,type:str]
    password: ENC[AES256_GCM,data:x0/74+VrqLA6eeZi2I4qLWLOrXjk9NZqCrEf3E+q4yY=,iv:BYjxF3CECOFinY/tPrkIK6Y84zScDGxOqpBa9IXyXcw=,tag:xANwnox5jCMEyZV5285pyg==,type:str]
sops:
    age:
        - recipient: age1axd89qsnm60jcgde249ehj836cmvacfl8pxxn92xnd62d8t6rexqk5r6u8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRQTl3eDI5dUV6OEswR1pL
            Q1JBR3dUTXJuVW5kZVh4MjhBOUNTbWFwQ3hZCmV1UFB0S2RsclZtSXFOTDNqSEls
            a21KUW5EdzRtN2I1RzFwYjNNQzhPUm8KLS0tIEd4ajRkZVg4SGM3QnlRdFZNR3dr
            cFJXNXo4RTlZTjBGSXFtTUxySkZSOXMKHhu0f4mAIGnVg4RlREXVNUr7b3LRA6xA
            AEa7xLPe231kZoxetDOHpLEef7QaXVBOEW9E4EC1VWK3veUQnpWFuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-23T17:37:50Z"
    mac: ENC[AES256_GCM,data:QyCLeDnPNTQdOa/sSSqjHeqmlS9Q1QOWKlnf45lg1ukgQLuChMwYTIHQlauqQKdcsHCWZtHELpdem5sa3CZOezoLy9BXXc9EkxJWLE/AlU6O3VZMf2vuLvVAGf6Ua0KTD97RXvkVBkGQULcEoBu4/kaSgzL/Hbxd2MxNSfLk2GQ=,iv:sgVjhQmsvOWFlwhrJHWWCdf79pd3D36CtX0rpXr+PyU=,tag:yNT1b58eXQ7SYYljIqK4Pg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
