apiVersion: ENC[AES256_GCM,data:Pfs=,iv:zzThowRcKYvhUpa9Dw/ghuPzIjL5RSAMJJ5TQG0Voqs=,tag:UNsWfy07rx+gYWT1V5QpAQ==,type:str]
kind: ENC[AES256_GCM,data:w4L4ziNe,iv:0q85ecm7bOcN5Jxc/Dat9YCAS9k82RKmpoiAMP98N9Y=,tag:WsR/3P9doSlROKT6zEat4A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:W3qvIwGKwnTq,iv:STPiVLjrPRUvL7Aj5kxxdIMq3TC8fRgX2EMyoLM07uE=,tag:6TyOWCiFq8EaAjNFx60weg==,type:str]
    namespace: ENC[AES256_GCM,data:rmmo8nVLdA==,iv:HIfFVZ/DobBqT2XABj2QmOGkPpvrvPz5ZU61DGHWFO4=,tag:SA0WO4HHWcDHgXj9r/htFg==,type:str]
stringData:
    message: ENC[AES256_GCM,data:AsjYUlOPpE8/ZegqYjfHv6EJEjVm,iv:h168MF7iIXptm1Ng4pUSxPwdy7tV7tPX2PcHgMpukJ0=,tag:u+U0bgLj5NgCDGl8dHjU0Q==,type:str]
sops:
    age:
        - recipient: age1axd89qsnm60jcgde249ehj836cmvacfl8pxxn92xnd62d8t6rexqk5r6u8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNTk1dVA0SUZ0ek1HMHVa
            NVRNQzBNUzl3c3lTYUUvQVd0S2o5REtSdlNVCkdnalMxNzlBREx1bDQ0U3dIYmU5
            b0pvVUIvenM2VmsyLzBCeC9KTmY4K0EKLS0tIGdrSEx2VlNCdWR0d3RNZEZSVWd1
            Y01GVlFSZWhSOU9XV21wRURDbXZZZGsKg7spPnMbK8GdVySlbZLk+vHF0lnWV8Tv
            T0sQ1EwwuE9WFq2SZ0FyfYBrWtZMoVNXWV2eHfS0LoRAGSxNv0zo/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-23T00:03:19Z"
    mac: ENC[AES256_GCM,data:rYdfnt+tSV6p2kQGQtstbrG4BT+ZvYzT1aoERI6M3sj4iIqSB68Y7ZOWF6xDKcSPu6F/HqBlT+cQDNCvWopwDcgS82L3wpvAQBx7Jg2aAXY6L7WTVeGZlfEFlzpUN0Z3i8qo/TMpgbrlrj4qKxlkGT6toghFXaCvrS3Jx17A57A=,iv:14lweaVHZDKBnM8xwXVj3tyeegqBqzyygDObyObtlQs=,tag:uwHs2Nr09e4+9MFd/eDCqA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
