apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepository.yaml
  - helmrepository-runner.yaml
  - secret-admin.enc.yaml
  - secret-db.enc.yaml
  - secret-oauth.enc.yaml
  - secret-runner.enc.yaml
  - helmrelease.yaml
  - helmrelease-runner.yaml
  - httproute.yaml
