apiVersion: ENC[AES256_GCM,data:mVc=,iv:pmFnd0Izp7eT6POzK4IXOa5zqZhx1WNyofNl5N+wfoI=,tag:WJzefCGULiG90bPpYnXPCA==,type:str]
kind: ENC[AES256_GCM,data:ixkZrDNH,iv:+PDw2OzmpQJh1LVIGiCRrPufJ7PqYT3ZANAZE2FzS7Q=,tag:TXQIDn6bpad83dHn4oEXiA==,type:str]
type: ENC[AES256_GCM,data:RmQ7trWZ,iv:mMTaGk9lyPZDibEIBImsFwFksC9xmbcXCd+duad5vEE=,tag:0rTJb5d8vOCRfByyqT8duA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:LSjjIefVVClFUsqGWg==,iv:6xW1u8r+9Zb6VwJwvv6NiSpy8fNpx8P85nDc1+W0gjQ=,tag:GpQMhbYt6qqklILkTNXFSQ==,type:str]
    namespace: ENC[AES256_GCM,data:yBWgp1VTdg==,iv:qvMB3CDWGnUXl2joUQdv7F4uADQCW4Ai0ttGtfX06PA=,tag:IZ0SVqgnXTOLFrB71YHWBA==,type:str]
stringData:
    username: ENC[AES256_GCM,data:lvj/5vU=,iv:3G7m0qvim7SIKXIrmAUMTS/MGD6dotbVnvQCXgdR1L4=,tag:o4/7NidByOcQpkaaYr3KZg==,type:str]
    password: ENC[AES256_GCM,data:8GLqROHwf4nYdJBkl49ZtLJkkJkRZitg,iv:7x5Ajx7k+/xLvHMtTcj221AwEnN1Cn+yZ5dDOe2z4gU=,tag:aYxDueoO0Gb/sKBVlkFJpA==,type:str]
sops:
    age:
        - recipient: age1axd89qsnm60jcgde249ehj836cmvacfl8pxxn92xnd62d8t6rexqk5r6u8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQaURReEhFU0RqZlRqN2hk
            eFZpd2szZ2ttUmU1QkE2WTE5OTJsenNiU0FjCjBtcGZYNmxVd0pEbkRiVVdaL09k
            ajZlazJUK1ZndUU3dmVZS3JlK3g3TXcKLS0tIHFHcVltMFpxazVIRUhaOWJsTHNN
            elVQUXlKZmE3NVdOaHFQd3RFd1dvRTAKb6PVKgqSc4Ac04njWi7187SECZT36pdv
            H1A3PfyeH0Zm26czAGofZ4GkHx9f1sn2hqDSBnzvf2RbcyFQDxpu8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-24T23:34:23Z"
    mac: ENC[AES256_GCM,data:nbwffzBFRH5t3KNWKFaxcS0A+nBiw5Vmsebl/gnciztUu/a0qGzf8QbHKJvyZ9YycVI/SIFxnJrs5l8+99JHePcT+5Jy1P4oGOzOca/QYAOSHoWXxxjxsgEIY1lTd+Ai/SPr5lVzbpsVUWkR8mDcgPy+BLX+TEFaef2lAZY6y5Y=,iv:IxllP+yIw+C0dkEIQxutmbVflzyxGwKcfYD5LNxGe2A=,tag:Sor5cRuDhujz0ruWjJuKog==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
