apiVersion: ENC[AES256_GCM,data:3b0=,iv:4wUBzGT4fUnaMPaKjd/QxbYMAHa0Clgf1UK643GMOCU=,tag:iqQt9+uxPaO5L1vAMDS/VA==,type:str]
kind: ENC[AES256_GCM,data:ssD0TwQq,iv:bVsaV2fYYEy+A5F2AP88LrYSqmF843Hb8hK8L/gYWn0=,tag:6EUi7TLUNpmt63AXf1g4rw==,type:str]
type: ENC[AES256_GCM,data:9AdpEEsV,iv:dbh0uMiNm5KJ1xrCjyfeYTNdonCkQYeeFWWD5hvpE/A=,tag:wbC5N9CWQvrlGU+MB9koaA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:oPYxspfX4ISzJrVZjQ==,iv:Ep9gyZmxcjfLscIOFUM1+wXqh5q6r8Qf2c3bpPzVx58=,tag:S0SCFxDBeSbCvksdtvx0+Q==,type:str]
    namespace: ENC[AES256_GCM,data:nBllQsDUaQ==,iv:IRvP65Ec4TmSh22QVPyyzI0vlpDKZ3bO2iDfnV6fc0c=,tag:tHOrflc+GgESGD0wt1Xy6Q==,type:str]
stringData:
    key: ENC[AES256_GCM,data:a8wV7PpTUaVOz+B95YTp+4YgMg==,iv:8z6cVQF9pp3OVdrbjkkqDJmJwxgNDymEUAarxJdrPt8=,tag:9+e+fnR6vTGd29/lyQuMew==,type:str]
    secret: ENC[AES256_GCM,data:zPajfAVW8LdP12VBSerGjMG4jwIjZ6I=,iv:qO1n+KoTjb5Qu+ofCM0WwBFrv9ycQ7LA1xTSr3JD80c=,tag:0w0sW72l/Hj/CJhWSgP5hw==,type:str]
sops:
    age:
        - recipient: age1axd89qsnm60jcgde249ehj836cmvacfl8pxxn92xnd62d8t6rexqk5r6u8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBITVdJejdBNnRwZ2ZPdTdt
            QlZRRFg0MTc4U2dnWFEwS1k4YmZHR011Z1hjClE3eFh1bXVoODdjbHRvb0JTVFNL
            cmFjT1VHTG1JcGdIZ1VNTHpLMFdUV2sKLS0tIFlHNHBZNE9paUlqdW5HU1A2OSs4
            aGdhTld1bmJaUUhEa1haU2JkaDJXQzAKdi3xmnL4n0DfXaT6lcfLHja68QXH8FVN
            mfoLzniPFF1coJFMHsnK3QOru2sRT8UgfR5aiVYE7Nr3+4b2ou3KOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-24T01:47:53Z"
    mac: ENC[AES256_GCM,data:R+kNNLmlrSBRvqgXZXC7WaZ6wKgvRSVJAjny+BAOelvsFB7G7YFJSe3Y51jGfYqfUMT8rtKa+SowOOGPAcPIomD6FAmfFcRcU/Ejh7SiMP8ba35CO+w+QlD2VTmkuZSNwN7aReZnS2IxeKs9lSjrXh1nE4zSCm5vvftvJlKChJU=,iv:bsI3foZbSmMUdMxn4busUTeKzbnEv4bfeSn+nguTM+U=,tag:ZzGbCoEHxV7C9P5hqnEF/A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
