apiVersion: ENC[AES256_GCM,data:14k=,iv:MFJOnStaw0oa3UJfYQ4Cs/GVNyXcC1VLB2oGSNGAd6U=,tag:AxsfIgVUViGQmTLpU1BZNA==,type:str]
kind: ENC[AES256_GCM,data:9pqhWbjr,iv:Jorp7zvFnwHHIfDrg02ES5ewER7vJasNSfF2K24kCXU=,tag:M2J+bJbSDZJCbipnmn8ybg==,type:str]
type: ENC[AES256_GCM,data:Mi2un/25,iv:pbN3NlMC+c+ibCcNm/Yxtg/oKcCawgoZCEBq5X33YEQ=,tag:H5k1MtItiw6E+72l1FiIKA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:LEOtFggA4sgIyobpmiQsf0U=,iv:7iTbdMENFqfP9N2Mwl5dNyGNxRdsf6kzjUEnMAQdtoY=,tag:kFGan7VRVmHYG5C9D9KO8w==,type:str]
    namespace: ENC[AES256_GCM,data:YOyA45iN9w==,iv:Flc24ensf/svdiH0Uymd+it+JfcuvzLnyju580ZU1RY=,tag:StSUIEAFwNHTfApE34PGHg==,type:str]
stringData:
    database: ENC[AES256_GCM,data:Ly4M3qAv09nC9O022UKihs3LHeYruLE/gRb79wlX5XTvQzB4ekdl8Q==,iv:ovrdnqqFWs7hyfxZqjMY94l8gyTH877j3srfHGF4o0c=,tag:6DFCDX24bUv85uNZO3/C6Q==,type:str]
sops:
    age:
        - recipient: age1axd89qsnm60jcgde249ehj836cmvacfl8pxxn92xnd62d8t6rexqk5r6u8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5d3RPRzA4NWxJeHFYZmEx
            aEtwb0pBbmc2ZjFpWkJ4Nm43Z0RsaTFYWkJnCmdNMUIvWnplenJWcEtJeXd2bW1X
            RzdaeXYxaDFONHFhRmtCYzRyM1N5Mm8KLS0tIG1QblBCMy9RZlVTVEs2bkQ1NTRp
            SDZtZFk3YkNTVWV1ZXNadDcveGlraHcKxmqrvzAZqOyr7KvjVH13EzYW4Z77cQGI
            kANIPyRf7iw10fAsRVO2awptrGNhSM8wPADYFjZNoummDPgjTP8sUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-24T23:34:41Z"
    mac: ENC[AES256_GCM,data:hT+qDKc9OnYX1Onlq31JvTaBA+u570XgpOJ188jhkzej4+U8+78s6HNN8f3bjxtA2J3KsPUwxrpqtnvPEK7RRnjqsXYFcOnF1A/jJxmJeDY8tKGGMPBvnEE2T/C9Dzzx+FhQC4QKs945E00jzxb25oRSQ4fWuI2rBqibORsEKjI=,iv:cizEe84OTzRuoLV1ph5HroZWGhumbF0m/IXHhv8xYMU=,tag:+vev9QZH3sM8JWjOYgsYAA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
