apiVersion: ENC[AES256_GCM,data:3b0=,iv:4wUBzGT4fUnaMPaKjd/QxbYMAHa0Clgf1UK643GMOCU=,tag:iqQt9+uxPaO5L1vAMDS/VA==,type:str]
kind: ENC[AES256_GCM,data:ssD0TwQq,iv:bVsaV2fYYEy+A5F2AP88LrYSqmF843Hb8hK8L/gYWn0=,tag:6EUi7TLUNpmt63AXf1g4rw==,type:str]
type: ENC[AES256_GCM,data:9AdpEEsV,iv:dbh0uMiNm5KJ1xrCjyfeYTNdonCkQYeeFWWD5hvpE/A=,tag:wbC5N9CWQvrlGU+MB9koaA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:oPYxspfX4ISzJrVZjQ==,iv:Ep9gyZmxcjfLscIOFUM1+wXqh5q6r8Qf2c3bpPzVx58=,tag:S0SCFxDBeSbCvksdtvx0+Q==,type:str]
    namespace: ENC[AES256_GCM,data:nBllQsDUaQ==,iv:IRvP65Ec4TmSh22QVPyyzI0vlpDKZ3bO2iDfnV6fc0c=,tag:tHOrflc+GgESGD0wt1Xy6Q==,type:str]
stringData:
    key: ENC[AES256_GCM,data:lIVrgaO77lkLDWa/pcSRTko7ICbZue2lIVCF2LBqg53Ql8Uo+fKX2A==,iv:SAppCSycQRNRb5Zd69Um3dtbxpYM+KlFdMKfigRufTc=,tag:jjHd7SLSXTbnM0K5osksNA==,type:str]
    secret: ENC[AES256_GCM,data:UYW8xISIeF6xYXzCBJXSSPKJrd2RXNEo2HNn0798+hKk1+5OFxkbf659ZsE=,iv:RBKOBgaKa8lSJk2sP8vxb2wRHDNhJEssKycGzAkeHS0=,tag:jm7U2f5It9bDyh4ViJCYjQ==,type:str]
sops:
    age:
        - recipient: age1axd89qsnm60jcgde249ehj836cmvacfl8pxxn92xnd62d8t6rexqk5r6u8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBITVdJejdBNnRwZ2ZPdTdt
            QlZRRFg0MTc4U2dnWFEwS1k4YmZHR011Z1hjClE3eFh1bXVoODdjbHRvb0JTVFNL
            cmFjT1VHTG1JcGdIZ1VNTHpLMFdUV2sKLS0tIFlHNHBZNE9paUlqdW5HU1A2OSs4
            aGdhTld1bmJaUUhEa1haU2JkaDJXQzAKdi3xmnL4n0DfXaT6lcfLHja68QXH8FVN
            mfoLzniPFF1coJFMHsnK3QOru2sRT8UgfR5aiVYE7Nr3+4b2ou3KOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-24T23:35:05Z"
    mac: ENC[AES256_GCM,data:GuMGpkXSrIur32+wwojgEl8GqWxhWrPCf0C2naArjaLWTz63XhVREPa+qXY4wLT4m6D+7B994pxSF0FL4XzRU4CXCssuGHnQQucqQMNpxM6PZtx8l4QTuNh+04UNgxypQu7p27nwu+Js6d7oIbwilkSjsjP0cxGxzEILFjR7g9Q=,iv:4lj/tejDU1lydhWAOC/RUbwcbvTcDWncmszwWGk5x7E=,tag:4FROCxHH7qWAsNI8jA6IRw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
