apiVersion: ENC[AES256_GCM,data:A1E=,iv:b2XM+3imB7DlcPqzV5bQ3rlWGqVdzO6q+VyS0vXmYHw=,tag:XD7/4jW2xGwjgm3rtAbQ0Q==,type:str]
kind: ENC[AES256_GCM,data:1WJExaOx,iv:ss5XgTUuxAcj2h53xogR090Nc2ZazDzWV57VngnFek8=,tag:N5pOzE5sOlctbnIpmXXzrg==,type:str]
type: ENC[AES256_GCM,data:nNGJd7Tp,iv:SjdRdU+KW6Hk0zCubnCbSVaaDxpjr6FqSzMelgwCvh8=,tag:ioDmkVQ3F5BzOrxvhmpD4Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:yDsP6nfBqNc8ObZ+TlVsELGP5g==,iv:h0KsFu/jVssfqBmwOIvOkFHLTvG7+X0MclsENPyK/Pc=,tag:EFEP6z+xmphjXX79MJbdZQ==,type:str]
    namespace: ENC[AES256_GCM,data:/BOUgSXytw==,iv:MS7kI1g5CEAGXYpL5a3HLaKhBQ3u44Vydj8aL9vvqQE=,tag:Mgb6Re24UyD9hgj6fAuH/g==,type:str]
stringData:
    CONFIG_INSTANCE: ENC[AES256_GCM,data:j4tb7/5TX1UFikjEYebnIC8vp6HT2kUiEyizzoBsTF0dJQkH,iv:hEK+9VLY/YhILicghiILC+NN0qORCWzQ/llITxel1os=,tag:rq6nKQZRYU7FIPqnuXqyhw==,type:str]
    CONFIG_NAME: ENC[AES256_GCM,data:6ZTTctleJGzJlzEx3y3V,iv:fFYz8P1j/BV/TI7MhtSB/TthuUBtfUwieGwiy/FrqCA=,tag:KXHaKP5/QpurvCLx91mkTg==,type:str]
    CONFIG_TOKEN: ENC[AES256_GCM,data:+LrQOvXMjqwNDVGnOIVFhzuDwnmgqxgk7fxxuxUEPqTv/2C5upamLCyn+A==,iv:EYu2KVzl2U3Egvf54uSheMj3OC/FAam+zmOazwkgIeU=,tag:pl4ZmhHKvH44XShAbr9LOA==,type:str]
sops:
    age:
        - recipient: age1axd89qsnm60jcgde249ehj836cmvacfl8pxxn92xnd62d8t6rexqk5r6u8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzNUk5QS9ENnIvcTNlNVB5
            d3g2WXdjVjE2TmNlVzJrTkdpcEcxMkhBMVZvCnZ1TzJNVW52SUpBaFFuTFZCTm5m
            eFBmdksrc3l6SkJaby8vZzBBK3pMVVUKLS0tIFU3TU9YQzRpZ2ZRZVN5QXBTaUpm
            c3YrUFdyRDNpZHFuM0ExTHJtKythL0EK8jBZ58j/Y+H3xk5q7VYgcFzgOKGBu1Kp
            D7pqiEhHmjp/7WO4NnHGUjeYUCn6csrsMMYPgnKdTlvU9RwXwQMKIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-25T01:12:47Z"
    mac: ENC[AES256_GCM,data:l/aHZ2CV+l5Rhtv5EKi7ZEG9Ij8YgHNNRdcwDtVBPP2BB4cLhLI+W0ppPd7vRKpPGzZK8ZwNSuhtH0K9pBUCc+6pa5bnFb9zarS2FSRCw/8IAoNFFBz3ATZV4zTKZaRLiZC1Sbep/d3vbI/JYfeRC88UwVb5+XYSkD9dsHAAArk=,iv:GtgDGdkZ4eCBoScLi+ScilBQl8BeP4atlas9ktdmwWw=,tag:d0bflubp3lfasA1XtVkELw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
