apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nfs-provisioner
  namespace: nfs-provisioner
spec:
  interval: 60m
  url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
