apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager-clusterissuer.yaml
  - traefik-certificate.yaml
  - monitoring-httproute-grafana.yaml
  - monitoring-httproute-prometheus.yaml
  - monitoring-httproute-alertmanager.yaml
  - monitoring-httproute-alloy.yaml
  - adguard-httproute.yaml
