apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- infrastructure.yaml
- cluster-policies.yaml
- apps.yaml
- provider-alertmanager.yaml
- alert-flux.yaml
