apiVersion: ENC[AES256_GCM,data:HXI=,iv:7qWtulwX5bbK84lIpHfnGkJ1Nm40j0wscgOFhVpYP2k=,tag:omq2IPX8RUti9xw1XZR5fQ==,type:str]
kind: ENC[AES256_GCM,data:XLemawI0,iv:OLtG1rVqsvwaZEtjRZoFTV092fBznnZ4Q8f+7VZSZUA=,tag:vUfEdwd0FOxmU4C8+oTFSA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:1G4InKxKjGaFbiVoT2FpskLWrw==,iv:CrUfLnMkIl+TVDpFTdz4HicEhe+/MTb260UcQKg9kPI=,tag:oStlO/9j6dBpA+lsYSy5bw==,type:str]
    namespace: ENC[AES256_GCM,data:TL3UX/Z9QQ==,iv:Z167FcCwGEny7WHv+yfE/e4xL9aA8kdRa3KU0VyVwoQ=,tag:IN/YsW+gf7iScZFPOPak9g==,type:str]
stringData:
    values.yaml: ENC[AES256_GCM,data:VjxesE1V5KPuKiwtpT8CwKJ0HODp9rzS1EJbqrHGZPQciRDhQJ+kCZbh1yoQwB6sOejTmHYhxsIKJx1yMgmJSfqAwXQN2l9q4yQTzHaXm3dJK6TJ04JzRKbba6KMHOqz3iUTobn+dOx6GCTPo2J506hU,iv:RHcPIXAlInE3W2Xf/ltQ9RdsJHUCROHGHv36/bZTmNI=,tag:KM7PRfoEmp6G9QSiwrFo+Q==,type:str]
sops:
    age:
        - recipient: age1axd89qsnm60jcgde249ehj836cmvacfl8pxxn92xnd62d8t6rexqk5r6u8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBORWt6U1g2eU1KV1FpOXla
            alZkRHFzczRUUGZ6b1VSM2FwbkxORDM5OEF3CkZEWWppVkFoeUVjbFJpYmYxZ3l6
            Z3VPUHFBQkVMZ1FCc3FzaEdSRHhXWGcKLS0tIE5sTWNYQnI5b1dsbkF6UHovWmhG
            WlpoajZXUk0zbUlSNHJYV3B5K1NEL0UKtZh9sXlhg5/uSbbE7kSg6240Gwn9J8dP
            j9kCgkJb4hHWpoTDqXQC2Sqz0CeGhPs6zoTz9N60SYp2i9YJRjYCUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-23T15:54:57Z"
    mac: ENC[AES256_GCM,data:ToSToRcM1xQS7wlD0zeX+CGspsZev/tKnQP3NteaAAOLv4prY6ioFmoJUKTjVAlaQfw2Hx6olc6QWCemApT6aQU7ak024WZNReY22DY15OykTY77HGgyjq+2FYtWgH3jCOOIPeAkzWXwY+nKJRav4UtNSDMhdT4A5tJXOeSJV2c=,iv:k8uMm5fH2B2dLwd7K83XEtQ+JFW8SICDmXopgMgIlKM=,tag:v1kmg1U+sRYdDxnQfYOVLA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
