apiVersion: ENC[AES256_GCM,data:HXI=,iv:7qWtulwX5bbK84lIpHfnGkJ1Nm40j0wscgOFhVpYP2k=,tag:omq2IPX8RUti9xw1XZR5fQ==,type:str]
kind: ENC[AES256_GCM,data:XLemawI0,iv:OLtG1rVqsvwaZEtjRZoFTV092fBznnZ4Q8f+7VZSZUA=,tag:vUfEdwd0FOxmU4C8+oTFSA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:1G4InKxKjGaFbiVoT2FpskLWrw==,iv:CrUfLnMkIl+TVDpFTdz4HicEhe+/MTb260UcQKg9kPI=,tag:oStlO/9j6dBpA+lsYSy5bw==,type:str]
    namespace: ENC[AES256_GCM,data:TL3UX/Z9QQ==,iv:Z167FcCwGEny7WHv+yfE/e4xL9aA8kdRa3KU0VyVwoQ=,tag:IN/YsW+gf7iScZFPOPak9g==,type:str]
stringData:
    values.yaml: ENC[AES256_GCM,data:bhpKz+r1ViD4hTpKDQLFbVJDYF0WmhF+jl4hx60/e1t7X+L3KocozE/5q9sfkQzbOFG/H+WR6IUrQ7wfy6/EK7bw7TjYXi/3T3tNVQTrgmnVyH0U2ceZ4xCHXey6onZJKKlzkOuV6bgno3a94wXIOLkmxsrdrkUUVd2eeBVb1Q+Coe1VoY3Wfa4dSBvJrdpX7Q61xeHbe6tg5yUFBVlsjflG35QPXXDHh2ZVAnlkOJTEBEOmdfmHPC9+vcpnZ6iei/gQ71h7+RAx2QI1lXEKBsjDSopz9tO3e32O3kFf3NweALfBVlJtc142Ukrke9TxDarPpK6XmffMOR4pBnwMkJpfEDMCLmB9cIbXowpJGG7trlWatPdrOczbnYc=,iv:D2QEnEagbxTy6TpWuGgq2CxHRlrg8MMuzpOwJvof/d0=,tag:jxSsSyEp0GDRo0RaZYZ98Q==,type:str]
sops:
    age:
        - recipient: age1axd89qsnm60jcgde249ehj836cmvacfl8pxxn92xnd62d8t6rexqk5r6u8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBORWt6U1g2eU1KV1FpOXla
            alZkRHFzczRUUGZ6b1VSM2FwbkxORDM5OEF3CkZEWWppVkFoeUVjbFJpYmYxZ3l6
            Z3VPUHFBQkVMZ1FCc3FzaEdSRHhXWGcKLS0tIE5sTWNYQnI5b1dsbkF6UHovWmhG
            WlpoajZXUk0zbUlSNHJYV3B5K1NEL0UKtZh9sXlhg5/uSbbE7kSg6240Gwn9J8dP
            j9kCgkJb4hHWpoTDqXQC2Sqz0CeGhPs6zoTz9N60SYp2i9YJRjYCUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-23T20:58:22Z"
    mac: ENC[AES256_GCM,data:FXxnyIb0v5ExVwMWmjymqRELobyNl7hBC8DGQnBzsUQkZpC+5LpUTrAJ9SrbWg9uHnQ+5is9sBCxwsTQLEe+Kao9ZkfkoH7BXtRCcbMWA359YlYCKqgqwcLYO0UqXtEyPsO/PSilZ3xXiyAGg2uC/+DR7aVTx04apu6T3OU8mTc=,iv:F8FVnfrDVoMQqsGXiFBZyXhUjO5wD+5I4N3U69yck/E=,tag:kS7dYLYcSQkmAYlVMNsoiQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
