apiVersion: ENC[AES256_GCM,data:PTI=,iv:LX1Y+k/Mva6Cz1tf1BXM/SlP6oo3ItkwCnE4zCVviQk=,tag:d5L4VtDvWDlCMasaczg43Q==,type:str]
kind: ENC[AES256_GCM,data:/Pyi68sN,iv:dHC84OxLy6TlTm+2JtR2TTnlJVfOnON7qQJjIRt8XG8=,tag:P851IPhn2GqiCo2+PEhbYQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:OJQ5laqCqhPBM+k/eyoatA==,iv:wqS96gEOBblokfCA8ZkfIkruLCSd11snOcaUeaTmFrA=,tag:D0RIL//O9tYW1YRMgh/vdQ==,type:str]
    namespace: ENC[AES256_GCM,data:nb4IfuLbVNT8hOy5,iv:pDmsIC3Mc4g/Ze9O3RVr1DxoD1cT80kgOFfudTZZznc=,tag:D7mA8jy2uio9pJum3OxEHQ==,type:str]
type: ENC[AES256_GCM,data:Q0161D8r,iv:M/mbTRdfK38lp48bqOwBk/XDNbFGj57w7pI1MZYMLMA=,tag:kc4JYHNxEg3TRkqdW9Qnmg==,type:str]
stringData:
    access-token: ENC[AES256_GCM,data:ZgHEvBWY+j1EPVVFLPcw1poGInHxWXuCHW21Yvfl/VhbBzlvyf8/XH09SZSJrQqLU9bBwmoCs9X8YFamKHe1+7+/sCgvJhA=,iv:wKXyoCbFpPB0lB4IjDAR4OoNfrSfle+EMR8UnfoQuyU=,tag:4ne9efMOKqyrn1wbJ58xvQ==,type:str]
sops:
    age:
        - recipient: age1axd89qsnm60jcgde249ehj836cmvacfl8pxxn92xnd62d8t6rexqk5r6u8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1QzkzVHd5RUFQempVRnhY
            KzlQZ0VxSFFwYnZubGhJdW9xSVVHS0FiamdnCm9XS0tiN1NVU2N2VWp0SjlyTmox
            RWUzMmFwSjVreUtrVFFUdzF0YTZmMFEKLS0tIHdaOE5adDd6QnlmaTJnZ2hINGVF
            QkRpYkpoV1BFeFpyQzE2L1k5MkJNS1UKOBRMbN9BpepKYmWGKex+9jIAfilp9FAw
            PmuPreUht9RYcSfV5SNKEsA2QieGiy5p0SqhUNBB9KdqGcc9bAj+dg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-23T02:14:48Z"
    mac: ENC[AES256_GCM,data:Cshok7OsaxQQ+sosyIA/fDGwX2A1HvwK7Ad63742jEAw5oTyTtmgmUz8sni/NeVSkM/strEY3f+fCsrrM6midKd+SDXpLSYNzP6LqZXUzOAlbszJzJQAPrtqjbNWFEhOr8HOjKKENEHALR9n4AC92Tfxo6m2Afcas3el/QaPq90=,iv:DwnYf3b+FF2ob2o8wyf/466ILhbGcaCFaw69R26uj74=,tag:/ThJ09+lvv7Gxf8tN4KgJA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
