apiVersion: ENC[AES256_GCM,data:+eY=,iv:Mtlc7XavBbcFAotvogxLywXLOqX9Feo+7e8gEoNjwAI=,tag:kVxQWCXyz3k5BEtzO7KhhA==,type:str]
kind: ENC[AES256_GCM,data:JEt6/2Zc,iv:+B05/IxvV5uwAPEA1IpQhY4z+BDN0BSMcTV4cZLepYM=,tag:Ccj3TNkEj++FleA1czfSHQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:FUUdp2YL3PODcdQSBg==,iv:ivjhVguc5y+0YLOEKtmbrWQRDor2Lr6L0aHtC4V1lIU=,tag:jHk+c7s0SYHpjKeeqapZOw==,type:str]
    namespace: ENC[AES256_GCM,data:VLFemO46pWY=,iv:mjRYTxDBhzQ2TFxUNr+YMY8+7P4gN/fG+MtoU6bR0Yg=,tag:Se9EArIroDqH/JkBhgwbYA==,type:str]
type: ENC[AES256_GCM,data:gMMPmVYz,iv:K2nZ7se5wU4AIzpO+N8oRrGOFN6pYm9l5QjYtVqs8qg=,tag:3eI1szzgmPt60OyBEvdW3A==,type:str]
stringData:
    HEADLAMP_CONFIG_OIDC_CLIENT_ID: ENC[AES256_GCM,data:ecFH3iTfupw/a4A=,iv:mKREYS+lqeq+T/3nHefTqt+xW/ALnOIg/o36HjuYwWM=,tag:Y57FPuyk+3CiElpNJ19MrQ==,type:str]
    HEADLAMP_CONFIG_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:iyOZgyLasL1xlmg=,iv:vcgcq0lGmaubsYxUniwTEDQTmi6fHz/oa4MjoHJ1vvU=,tag:Oy0SK/B4anerqNgVk9CCSQ==,type:str]
sops:
    age:
        - recipient: age1axd89qsnm60jcgde249ehj836cmvacfl8pxxn92xnd62d8t6rexqk5r6u8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4SjFyQVJDeWlZYWprdW5u
            U3RkOVJ6ZUxrMkIvZStCdXNjQ3UxTkpVeURJCjhnMXZVNkdzbm4xNUZKRGVKTjhT
            Mk1FQ3RLR0M5by94L25hWXlQRGVIek0KLS0tIG5GM2MxTTI1WW1XeER5UVNrUnd4
            a3JDYng3VElxRFM2Wmx2anNaZ0MwL1EK1PN1B7OLPc7q49pY4l7DRWk0Uu4W8rzB
            wpuZvRDzIQWi1BQxYmdeAJJfE8+U5rfmNozjr0GqH8WwCdNi3Sb4Ww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-24T01:41:40Z"
    mac: ENC[AES256_GCM,data:dXAAk0IZf1FF6sQCTtdgIj8i7XiymG1lHLemrrGT5P6wquSkhFxZ3FVzvORmNEI3vuFZGaujUn8/ciGISyDh7hGSkNJ8aMtiFOBaGOtKGUBWQe/Fmci4qfgFenq6I5Lv7MK+KwbFtFJkJ3CWY3RNfFTtN07pOgH/2XcolTm6DW8=,iv:M+DM4ny9jkHSZqYUBdcNVn/RPRyD75dbn8LuQOE7Qyw=,tag:VI03/rXBIf29G/oQaHgaUw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
