apiVersion: ENC[AES256_GCM,data:i9Q=,iv:MXudA7mbnvjaMNsInzvU/UQNvsYgBtAB0Qhpqeo9tIU=,tag:aYkMh8jTFKuumX75R5oILQ==,type:str]
kind: ENC[AES256_GCM,data:GL6fIxFQ,iv:4OlX5fEsWp3LBI6NNk3FYf6hjIe+akUpFDj+gOItRSk=,tag:LLLP+8rq29rUIMMVlCRkDw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:DwwMJrwbfuhpCcZpKA==,iv:R8hm/L8NEKiFXtIAIFajblIsXGDmKe8WbE6GzfIcKcc=,tag:GpLTC3dsATgXpWhWWssKWg==,type:str]
    namespace: ENC[AES256_GCM,data:E16a+5vwZ3w=,iv:8BlVdSV/e5SU3SJi0bkvyCO0hfygDDy4SKguOEnWHl8=,tag:WtWDZ3PfI93/Baifm6690g==,type:str]
type: ENC[AES256_GCM,data:kC76s0Np,iv:deigUbkf4Mv35R3PoGiMV/FPV9uD1L6J+P2JpWcoJBY=,tag:Jwy80gpeYDjC/oJxxkvL+g==,type:str]
stringData:
    HEADLAMP_CONFIG_OIDC_CLIENT_ID: ENC[AES256_GCM,data:VaqEVm1onghGJQQJs7p3HhdGObNttvJQU4CDf/ngts/bms6ll+Qwrw==,iv:MWlA7FHtFJy4els8G508S4D0O+UzfqLMNgPyp0eIOYc=,tag:mS0AwLe0HgWIFZ3zwfmAig==,type:str]
    HEADLAMP_CONFIG_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:JZG1auAx9oE+/PpPN2+qV7UcPst1tl6Ah1e5gMi5lA3L/vNTjnfpmYPUOf+9dnECeq3boKA431hfDZWQylFLjxrV3Wrt0vGenYs0a+p0LrA=,iv:Vx36cr9PwKYBkvPvqWSHaRpa+umO9R5feZZz2eyEJ7E=,tag:3xIx8CJAkMsVWICgHzxqRA==,type:str]
sops:
    age:
        - recipient: age1axd89qsnm60jcgde249ehj836cmvacfl8pxxn92xnd62d8t6rexqk5r6u8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOdTRsR2Q5eU5hbVhrUkZz
            amVJUE8reExiSlNpZEs1bEhpU3Evd2p5bnhRCmlNOUpQbk5hVi9rWVBkOXlFRU1V
            RzJQaHdTWW5SaUFqaXhlOFFvRnZqSVUKLS0tIDRXSXl1S1pSdTBDOTFmZGE5Vzlk
            aGdHb1puOHhRcEdpZUY1WnNHcldXZU0KBe04eEyzRgMTuEtlOvj4WzpZ5GMX8+yy
            /biHcraq40pq6f3K/foF2ZB0u5hXeTckNH0gltarR98rrXI0WR3VmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-24T23:30:02Z"
    mac: ENC[AES256_GCM,data:/BmFD2zJBTloVc30KP8gZycK2Dbw3BSfSxKkgaQir+VTgX3a64JXOO38F3uUdhK33VJORnn9+2Ko4s6AlRGsz6H2vGqY1x+BYFkhVI2/EcjJD0luSKiLyOlWsFTBT720S2BVmT+qB8ZFgaDWtIl5uBP4D+ypQvIBrPzXfbBpFSU=,iv:XsRCYd5lNCOFBQmh9xliOiuo7O0B8frT0NLONbYP6Ow=,tag:LDrWQFVcT+4mW9p2Gkc9hw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
