apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentik-outpost
  namespace: authentik
  labels:
    app.kubernetes.io/instance: traefik-outpost
    app.kubernetes.io/name: authentik-outpost
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: traefik-outpost
      app.kubernetes.io/name: authentik-outpost
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: traefik-outpost
        app.kubernetes.io/name: authentik-outpost
    spec:
      automountServiceAccountToken: false
      containers:
        - name: proxy
          image: ghcr.io/goauthentik/proxy:2025.12.4
          ports:
            - containerPort: 9000
              name: http
              protocol: TCP
            - containerPort: 9443
              name: https
              protocol: TCP
          env:
            - name: AUTHENTIK_HOST
              value: http://authentik-server.authentik.svc:80
            - name: AUTHENTIK_INSECURE
              value: "true"
            - name: AUTHENTIK_TOKEN
              valueFrom:
                secretKeyRef:
                  name: authentik-outpost-api
                  key: AUTHENTIK_TOKEN
          readinessProbe:
            httpGet:
              path: /outpost.goauthentik.io/ping
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /outpost.goauthentik.io/ping
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              memory: 128Mi
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
