apiVersion: ENC[AES256_GCM,data:Aag=,iv:iaf4QUNI6HWdy5I1JHEB71lhPm0bN10eUet9MHVbngg=,tag:7p3Hvnt4hSqErBvqu9Jlmw==,type:str]
kind: ENC[AES256_GCM,data:Qdc8AcoS,iv:HCNjo9iox6VD5NBAjzfTKsXWIsFp8Jsa5JLaCnQlCGM=,tag:O7u+6Qe3lNXB9oxt7JHIrg==,type:str]
type: ENC[AES256_GCM,data:x4+7YdNW,iv:qayOeBfvQ/rd19oj+fjAQ6+TynNhSxvL/VcuaAi1Rag=,tag:UDWITtPUC4pjjwnq3oipUw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:vLTC9Wy/Kaaz9+Moqbb59NJIz/EF,iv:jrhSAUtJXtSzMdQPV0iTzqgNHowVwAfjdcph6zD83r4=,tag:RTKx03nXG66I+o4bbe2+UQ==,type:str]
    namespace: ENC[AES256_GCM,data:+UEYtBXDbQY+,iv:BHfLXxgIBoYP32PBqQPwfv3ZIWwk0sEEpKEJjWm34E8=,tag:y54ZdgUE60EnF5O2A/SmvQ==,type:str]
stringData:
    AUTHENTIK_HOST: ENC[AES256_GCM,data:dpWwMCG8nwDddhQq/KvYq/3im/cPvZmb44g1yQ==,iv:thi5/Ma+irT72zDdNOECIA4CgouANiW2y5WciwFQo9E=,tag:vmW+Ufxgh4oDmVjJriHlIw==,type:str]
    AUTHENTIK_INSECURE: ENC[AES256_GCM,data:G/MJvw==,iv:+F1eb5bEsyWn9RPDl7nNAg+u1fqUjWror8tRE4A4e5w=,tag:4HwQ6gzNwQSdSN4zx8hAqQ==,type:str]
    AUTHENTIK_TOKEN: ENC[AES256_GCM,data:aX12PXfQ7msHxAYWnM3R1k316hrME0h/JWjv4KW556KpQZkp,iv:3fyKC390fZbaj0HuFea//I3luhGMGEGT5QORQU6LXRo=,tag:bEDrJ+L2LmJGA1vQZlNFEA==,type:str]
sops:
    age:
        - recipient: age1axd89qsnm60jcgde249ehj836cmvacfl8pxxn92xnd62d8t6rexqk5r6u8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Z0k3YUhLeWo1clpMaU5I
            NFVDY1FhSU12MUlSV2NUM2pNdzcwQkpNQURBCkllMjM5MVNuN00xWVliK2FZcy82
            b0tQZy82eVBCeUxpQ2FLTWYrQzFJRGcKLS0tIFF5cUdyQkdTRVJyamEyd3NkS29q
            RUNqZlJTL285bnY1WlM5ZHQvZUZYaW8KPCMxYakiV4cp/dYmeD09lBHlkGem+LAB
            oZKBmMlxDBGBsECgoPvX2FwA1Js+RaBFkB0o3Zfce5zWZ7fV/9yzvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-23T17:40:09Z"
    mac: ENC[AES256_GCM,data:42VHIxWKCfQviD8AvYyQOrHekLAZhP3exwTQN5G047Cj8EaFPMRWDn9o1pXwbh5zMni9uimYDxwsJgD7Pt8QBuKvf9IYFWtG484qsl9Hq7H7KD0FvzHY5iPHvnXR4MSa74moo+PnINB6grpxxnOUT5OG+JXW9U9ueff1OzOOBP4=,iv:FJRfCv/PstT/irJHqYMXM5M0ohWOq8jOGM9srn8r3u0=,tag:bjxDIDF1xrkN54aBMStr8g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
