apiVersion: ENC[AES256_GCM,data:Aag=,iv:iaf4QUNI6HWdy5I1JHEB71lhPm0bN10eUet9MHVbngg=,tag:7p3Hvnt4hSqErBvqu9Jlmw==,type:str]
kind: ENC[AES256_GCM,data:Qdc8AcoS,iv:HCNjo9iox6VD5NBAjzfTKsXWIsFp8Jsa5JLaCnQlCGM=,tag:O7u+6Qe3lNXB9oxt7JHIrg==,type:str]
type: ENC[AES256_GCM,data:x4+7YdNW,iv:qayOeBfvQ/rd19oj+fjAQ6+TynNhSxvL/VcuaAi1Rag=,tag:UDWITtPUC4pjjwnq3oipUw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:vLTC9Wy/Kaaz9+Moqbb59NJIz/EF,iv:jrhSAUtJXtSzMdQPV0iTzqgNHowVwAfjdcph6zD83r4=,tag:RTKx03nXG66I+o4bbe2+UQ==,type:str]
    namespace: ENC[AES256_GCM,data:+UEYtBXDbQY+,iv:BHfLXxgIBoYP32PBqQPwfv3ZIWwk0sEEpKEJjWm34E8=,tag:y54ZdgUE60EnF5O2A/SmvQ==,type:str]
stringData:
    AUTHENTIK_TOKEN: ENC[AES256_GCM,data:F006WjFsTZExlv0WJgTAJIi4CrkRH6gb6Kfz6b0qpS3PFeUK9rtrmg5mriA=,iv:/9XEoB/hGtaghkisrktLmX80WxeGLJ5ZIQnvFP8U4YQ=,tag:Qkd0Mx+88gYWoVjFvnXa9A==,type:str]
sops:
    age:
        - recipient: age1axd89qsnm60jcgde249ehj836cmvacfl8pxxn92xnd62d8t6rexqk5r6u8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Z0k3YUhLeWo1clpMaU5I
            NFVDY1FhSU12MUlSV2NUM2pNdzcwQkpNQURBCkllMjM5MVNuN00xWVliK2FZcy82
            b0tQZy82eVBCeUxpQ2FLTWYrQzFJRGcKLS0tIFF5cUdyQkdTRVJyamEyd3NkS29q
            RUNqZlJTL285bnY1WlM5ZHQvZUZYaW8KPCMxYakiV4cp/dYmeD09lBHlkGem+LAB
            oZKBmMlxDBGBsECgoPvX2FwA1Js+RaBFkB0o3Zfce5zWZ7fV/9yzvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-23T22:22:54Z"
    mac: ENC[AES256_GCM,data:ejYdQxHNtnTd2CZKeYsOVecf7bLPeCXkgmhZ9EesDYRPPI8MymNLrnRybqeUPvkjSo8USSoMKrtbM//eSfx+GpCU06FFj5kodrF3wdqdmHGUq8mX6PrXkncGDXHeOx0a6YO7J0/K2qqMgWdnYPxcYLr6EomQ2h1VeiphEobyM8g=,iv:vCPhX2XfjAWAZalbcFxPVf/e8kIFCDgm8d9+HduF2rY=,tag:ueykRU8wZigad7wW5oT5AA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
