apiVersion: v1
kind: Service
metadata:
  name: authentik-outpost
  namespace: authentik
  labels:
    app.kubernetes.io/instance: traefik-outpost
    app.kubernetes.io/name: authentik-outpost
spec:
  selector:
    app.kubernetes.io/instance: traefik-outpost
    app.kubernetes.io/name: authentik-outpost
  ports:
    - name: http
      port: 9000
      protocol: TCP
      targetPort: http
    - name: https
      port: 9443
      protocol: TCP
      targetPort: https
  type: ClusterIP
