apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentik-outpost
  namespace: authentik
  labels:
    app.kubernetes.io/instance: traefik-outpost
    app.kubernetes.io/name: authentik-outpost
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: traefik-outpost
      app.kubernetes.io/name: authentik-outpost
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: traefik-outpost
        app.kubernetes.io/name: authentik-outpost
    spec:
      containers:
        - name: proxy
          image: ghcr.io/goauthentik/proxy:2025.12.4
          ports:
            - containerPort: 9000
              name: http
              protocol: TCP
            - containerPort: 9443
              name: https
              protocol: TCP
          envFrom:
            - secretRef:
                name: authentik-outpost-api
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              memory: 128Mi
