apiVersion: ENC[AES256_GCM,data:FS0=,iv:/JaEp+Kz62kXxvqHpOsIMBXnkpXRdL6yjBGM2nDfFeQ=,tag:XZMctQXrRVmp3Xb0Srnntg==,type:str]
kind: ENC[AES256_GCM,data:8+168LBD,iv:As9am4Y4HG6Y8AgPNU2JGkvyyiEMY/0330PKoYbmvqY=,tag:3NqEGkSZtPpt9VWPm87fJQ==,type:str]
type: ENC[AES256_GCM,data:f4KfXnAc,iv:IHJIx4qGEoPrLusHx0nwIrzGDsVFkbe1HJ+bh4Jksxs=,tag:nndeOY4MwhQS4/164KZKVg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:NCiaqniPsKi3egO80XBC8/A=,iv:11YukrPsXpMRZ2J1BG5fhmOB8xAB5DUVtZjDYseHUZg=,tag:+1jC6ZPdD7l7h60t5BhS/w==,type:str]
    namespace: ENC[AES256_GCM,data:vQp9Vx5pd45f,iv:clx4k85b3OddRUzSWZJwRJFIUGlG8nSsTTN4o8wukoM=,tag:SOrkjEvjm3DsU1qrQjR5kQ==,type:str]
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:IkdZ5d0xE4GpoF8Tdt6N3q30wkRwYiuLqOe8iWCZtAJBgDhVxmJgAe1Icj5aM2Qnuot4GxN/KOqNLbA/Nr6E+ZIRKrA=,iv:TmPn1w8Jjmo2P7gsIg9ESCdv/Ed2tJBHFpgUqX7OLtQ=,tag:ITbbMJufoqdpOv5d90FFJA==,type:str]
    AUTHENTIK_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:uxr5XmU30etedXGt/4vf7Czixpf39yu313xhZUCAOu6CYMNj97xyNZtO64I=,iv:nn9pHcKcfIwxp0KCwfPFFwPWzJoEK3WK3ZV9WNu0tUQ=,tag:TTntalCBlPx8IHTP3SIvJQ==,type:str]
    AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:I2nAnx/elDUgUA==,iv:+DEkrz6GOMmwjd75V6OApChZXhm0uY4dqI7XDmOocpE=,tag:JJ1DCfc0lMdkv4ZsPULWeQ==,type:str]
    AUTHENTIK_POSTGRESQL__HOST: ENC[AES256_GCM,data:GrYUX4pYKpYIdd/R+aK5BdBFqOKaWPUE+cdHET7B0vK0hiItCsySrmGCRb0Ytw==,iv:ga+W66ZzPEUjbSMR4N9P5czguS1QtoZbGacLE9K5T70=,tag:Z6EsU3DzEp2fYGV2/5OYew==,type:str]
    AUTHENTIK_POSTGRESQL__PORT: ENC[AES256_GCM,data:RF/2wQ==,iv:6hpPZYWebq2KbvWwgj/676dQtlhV3Tai5mtzXNMZr74=,tag:DxCxGGgGzs5O5k/CPQGxQQ==,type:str]
    AUTHENTIK_POSTGRESQL__NAME: ENC[AES256_GCM,data:/MLn7R7anA/L,iv:Y7pIRb5lBX0BdHYl53kHHCuZNUVZK57nTHd4K/7SoCA=,tag:JtXT//KgsL9Z90gD9VZzNw==,type:str]
    AUTHENTIK_POSTGRESQL__USER: ENC[AES256_GCM,data:CmMN77gd8/yT,iv:SNtV3mBDEm3e9f53hPplLcjt7ExRfNhDPH68zTDFh6s=,tag:WZS0OHv4biBxVfCBwkZ4Wg==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:MBc3rkKVR0zYlHgGFfIp1Lr4KPlQ5foiWTHYsrcqqRnAsKVxmso6ZD8zsWg=,iv:cfhMeWEINos7yAGYoU/U6nq7PcHQrRW28ltNj/Xzt7E=,tag:z4qwiC8lLm3hybtuAk55yw==,type:str]
    FORGEJO_OIDC_CLIENT_ID: ENC[AES256_GCM,data:mZHEOtEvQEKXViC2nshee22QLEojrH2HQ6WRah80d+zqox9V7giYfg==,iv:MJssQHj5vUgiIEJJFhagAMcxkmMwTSRAz1gzRHEO/FE=,tag:N8usKCHCgkCqXmphWrB/8Q==,type:str]
    FORGEJO_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:q/azMvVTQQYcxtsInDiRTUVJUDYwwHebbejm6EMvZm9c9hXTmPMuTm3arxU=,iv:+44ZUU1OzXctWPW11O71pfJxhiVXURAnlA0viSOc0Wc=,tag:PeCo9nuykYl3UY0xDSWfng==,type:str]
sops:
    age:
        - recipient: age1axd89qsnm60jcgde249ehj836cmvacfl8pxxn92xnd62d8t6rexqk5r6u8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXQm5DUmVJbHBkbFM5bGxo
            MlBqdjhJc3VBcEFhTVZnVmp2VDFnZDFFcHc4CkE3clhTWktaNWl4MkFaMjg4cy85
            ZE5EVUltVmlKa01EUlZSMVIzRjhRdWcKLS0tIExtU3piZlRPTFZ1WjlUMWQwdEY4
            dVJQNWRFWGlXb2wxUnoveis1MlNPS3MKgQ+WSlltex4DKGJgDiKEo98wbP/n9Mup
            ZycjRDBq2IODwp8sBX1I3tHeiRj426YxLiresM0a+KSDFlM1Oc9MLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-24T23:35:24Z"
    mac: ENC[AES256_GCM,data:+7AQEPxxr8CZqrTRF1g7iFBhNJ9f72Fa0BcZiUftEbcEiS8HgM1NJbaz0XpMnLQWUoWDUSuJDG4M/DJ655/gYhVmM3SNbDHVAm/0OzdLACBcFWnYZfl0T1Y/AyBndyR0lfdeNPRfSZJwKnAgBsVraaAY3RXoF0llO+MvQ4VCk/w=,iv:r9LEXjytaacQJe8vU3lUmoT4h5oRXjRUzxSKu+ZudFw=,tag:Y38W9AzkEpE9Jq7sgmi6xg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
