apiVersion: ENC[AES256_GCM,data:FS0=,iv:/JaEp+Kz62kXxvqHpOsIMBXnkpXRdL6yjBGM2nDfFeQ=,tag:XZMctQXrRVmp3Xb0Srnntg==,type:str]
kind: ENC[AES256_GCM,data:8+168LBD,iv:As9am4Y4HG6Y8AgPNU2JGkvyyiEMY/0330PKoYbmvqY=,tag:3NqEGkSZtPpt9VWPm87fJQ==,type:str]
type: ENC[AES256_GCM,data:f4KfXnAc,iv:IHJIx4qGEoPrLusHx0nwIrzGDsVFkbe1HJ+bh4Jksxs=,tag:nndeOY4MwhQS4/164KZKVg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:NCiaqniPsKi3egO80XBC8/A=,iv:11YukrPsXpMRZ2J1BG5fhmOB8xAB5DUVtZjDYseHUZg=,tag:+1jC6ZPdD7l7h60t5BhS/w==,type:str]
    namespace: ENC[AES256_GCM,data:vQp9Vx5pd45f,iv:clx4k85b3OddRUzSWZJwRJFIUGlG8nSsTTN4o8wukoM=,tag:SOrkjEvjm3DsU1qrQjR5kQ==,type:str]
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:64QAgJwAHw5RxiBm6h4+7ZWFkzR8atHEyPLFcsRIhZhI/r/drtQKhQ==,iv:QrCJzj8j1gN+4miRwJRcqsMxX1bv658J/R7yDpNNvbk=,tag:RoOhM6jA6wVe121h9/RFAQ==,type:str]
    AUTHENTIK_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:u4PI7jG5vl30v7foDqkD3vg2VyBy3L60F7EdJ7YK,iv:tyHXXnfkYd6yczPLsua2/V5No4pN7Nkqj7vyoJULnms=,tag:NZYaGyswHRgUGHUcJ67v5g==,type:str]
    AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:3vavmXdjot6xUuFBoHGZ0T4fj/Yzi2eYv52wIQ==,iv:emez8T9Q7QSmL1hwoCbVoroxidzTu8uvbqPei4VTzjU=,tag:LOO9NUn9MR5/Yns4qGS+6Q==,type:str]
    AUTHENTIK_POSTGRESQL__HOST: ENC[AES256_GCM,data:GrYUX4pYKpYIdd/R+aK5BdBFqOKaWPUE+cdHET7B0vK0hiItCsySrmGCRb0Ytw==,iv:ga+W66ZzPEUjbSMR4N9P5czguS1QtoZbGacLE9K5T70=,tag:Z6EsU3DzEp2fYGV2/5OYew==,type:str]
    AUTHENTIK_POSTGRESQL__PORT: ENC[AES256_GCM,data:RF/2wQ==,iv:6hpPZYWebq2KbvWwgj/676dQtlhV3Tai5mtzXNMZr74=,tag:DxCxGGgGzs5O5k/CPQGxQQ==,type:str]
    AUTHENTIK_POSTGRESQL__NAME: ENC[AES256_GCM,data:/MLn7R7anA/L,iv:Y7pIRb5lBX0BdHYl53kHHCuZNUVZK57nTHd4K/7SoCA=,tag:JtXT//KgsL9Z90gD9VZzNw==,type:str]
    AUTHENTIK_POSTGRESQL__USER: ENC[AES256_GCM,data:CmMN77gd8/yT,iv:SNtV3mBDEm3e9f53hPplLcjt7ExRfNhDPH68zTDFh6s=,tag:WZS0OHv4biBxVfCBwkZ4Wg==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:VRN6rU2f5/RxKqRZqeBQnQVdEDIXfaLzAX1J2uZ9UIO02fxC,iv:T5ZatfGWwRkJU/ZFtYHDQ6OzmPZjh9Bi0w63XvxOM2E=,tag:k5kE+SToVg+pVQxe4sU3EA==,type:str]
sops:
    age:
        - recipient: age1axd89qsnm60jcgde249ehj836cmvacfl8pxxn92xnd62d8t6rexqk5r6u8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXQm5DUmVJbHBkbFM5bGxo
            MlBqdjhJc3VBcEFhTVZnVmp2VDFnZDFFcHc4CkE3clhTWktaNWl4MkFaMjg4cy85
            ZE5EVUltVmlKa01EUlZSMVIzRjhRdWcKLS0tIExtU3piZlRPTFZ1WjlUMWQwdEY4
            dVJQNWRFWGlXb2wxUnoveis1MlNPS3MKgQ+WSlltex4DKGJgDiKEo98wbP/n9Mup
            ZycjRDBq2IODwp8sBX1I3tHeiRj426YxLiresM0a+KSDFlM1Oc9MLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-23T17:39:08Z"
    mac: ENC[AES256_GCM,data:bEhse3Nk5GzK6dE+8kf5k96RfSZgInzlyFn3Nt4usht8eE0TTku+H4Gjr0S/fjKLI+Y/DRYNrEmeXPTY9uIzKrcS9d2GF/YACyKbHZkNTaQqi6S6LcsiqCenZ0m9ZI9UnSKuaUAp7vXNeNp3EjYk2TWcQPITT1cUnOgvWwNpZ4g=,iv:eabVRO+oC/uvWdeV0yDqOvb4dgmDmQilp0IYlKoNUOw=,tag:rgVpmeflCFpbXCn9pJ6MZw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
